import type { Resume } from "./types";

export const RESUME: Resume = {
  hero: {
    name: "Leonardo Sarmento de Castro",
    role: "Senior Software Engineer",
    kicker: "AI-assisted · TypeScript · Node.js · React · AWS",
    location: "São José dos Campos, São Paulo — Brazil 🇧🇷",
    blurb:
      "Senior Software Engineer with 10+ years of experience building scalable, high-performance web applications and distributed systems using JavaScript, TypeScript, React, and Node.js. Experienced working closely with US product teams to deliver measurable improvements in performance, conversions, developer experience and product adoption.",
    // Hero portrait — full-height beside text on md+; centered above on mobile.
    avatar: "/leonardo-05.jpg",
    links: {
      linkedin:
        "https://www.linkedin.com/in/leonardo-sarmento-de-castro-a249b945/",
      github: "https://github.com/leonardosarmentocastro",
      email: "negocios.leonardosarmentocastro@gmail.com",
      whatsapp: "https://wa.me/5512981276618",
      whatsappDisplay: "+55 (12) 98127-6618",
      whatsappMessage:
        "https://wa.me/5512981276618?text=Hello%20Leonardo%2C%20I%27m%20interested%20in%20discussing%20a%20project%20opportunity%20with%20you.",
      site: "https://www.leonardosarmentodecastro.com",
      resumePdf:
        "https://drive.google.com/file/d/17bOTWpjYsRroPucnWTzxIT9Q5GZ88UG8/view?usp=sharing",
    },
  },

  about: [
    "I work with AI-assisted tooling as a natural part of my workflow, and bring that same pragmatic approach to everything I ship.",
    "I take ownership of what's in front of me, stay focused on outcomes and move fast without cutting corners.",
    "I care deeply about the craft and about the people I build with. I show up with discipline and accountability, and I do my best work in environments where quality, communication and collaboration are taken seriously.",
  ],

  workExperience: [
    {
      company: "Pinterest",
      via: "via nearshore agency",
      role: "Senior Software Engineer",
      workMode: "remote",
      startDate: "Aug 2024",
      endDate: "May 2026",
      description:
        'Pinterest is a visual discovery engine and digital bulletin board where users find, save, and share ideas in the form of images and videos called "Pins". People use it to get inspiration for projects, discover new interests, plan events like home renovations or trips, and even find and shop for products.',
      bullets: [
        "Designed and ran A/B experiments tied to data analysis to surface the most profitable advertising formats for Pinboard, driving a 30% total increase in advertiser adoption within 3 months;",
        "Shipped CMS integrations, layout improvements, animations and accessibility enhancements across multiple subsites, achieving a 90% Lighthouse accessibility score for WCAG-AA compliance through semantic HTML, ARIA attributes and automated a11y testing;",
        "Led the full migration from npm to pnpm across a large, flaky monorepo, unlocking micro-frontend architecture and per-package dependency sandboxing with independent library versions, effectively eliminating class-of build failures and easing CI/CD congestion.",
        "Overhauled the team's development experience and weekly release process end-to-end, transitioning from Gitflow to Trunk-Based Development and building multi-environment pipelines (preview, staging, pre-production and production) with shared artifacts, parallelization and container image reuse, cutting 30 GB of data transfer and 15 minutes per pipeline run for roughly $1,000 in monthly savings.",
      ],
      technologies: [
        "Claude Code",
        "Cursor",
        "Python",
        "JavaScript",
        "TypeScript",
        "Node.js",
        "Next.js",
        "Turborepo",
        "pnpm",
        "React.js",
        "Sanity",
        "Tailwind",
        "Pinterest Gestalt",
        "Cypress",
        "Figma",
        "Buildkite",
        "GitHub Actions",
        "Docker",
        "Vercel",
        "AWS",
      ],
      lane: "right",
    },
    {
      company: "Blue Yonder",
      via: "via nearshore agency",
      role: "Senior Software Engineer",
      workMode: "remote",
      startDate: "Jan 2025",
      endDate: "Jun 2025",
      description:
        "Blue Yonder is a global leader in end-to-end digital supply chain solutions for software retailers. The company helps businesses manage the complexities and disruptions of modern supply chains.",
      bullets: [
        "Contributed to a large-scale micro front-end migration spanning CI/CD pipelines, tooling upgrades and package version alignment across a distributed engineering team;",
        "Enhanced the internal component library by resolving bugs and improving design system consistency across the platform;",
        "Expanded end-to-end test coverage by ~10% across multiple system layers, strengthening overall platform reliability.",
      ],
      technologies: [
        "Cursor",
        "GitHub Copilot",
        "JavaScript",
        "TypeScript",
        "Node.js",
        "React.js",
        "React MUI",
        "Webdriver.io",
        "Figma",
      ],
      lane: "left",
    },
    {
      company: "Hrizn",
      via: "via nearshore agency",
      role: "Senior Software Engineer",
      workMode: "remote",
      startDate: "Jun 2024",
      endDate: "Dec 2024",
      description:
        "Hrizn is an AI-powered content operating system for automotive dealerships, combining LLM-driven content generation, SEO optimization and multi-channel publishing to help dealer groups build organic visibility at scale.",
      bullets: [
        "Sole front-end engineer responsible for translating 50+ designer wireframes into a fully functional product, taking the platform from designs to a working beta used by automotive dealerships across the US;",
        "Built AI-powered features including LLM-driven content generation and automated SEO optimization, enabling dealerships to create, govern and publish search-optimized content without manual bottlenecks",
        "Worked directly with stakeholders through the beta cycle to continuously refine UI and UX based on real user feedback;",
      ],
      technologies: [
        "Cursor",
        "GitHub Copilot",
        "JavaScript",
        "TypeScript",
        "Node.js",
        "Next.js",
        "React.js",
        "GraphQL",
        "Apollo GraphQL",
        "Tailwind.css",
        "React MUI",
        "Figma",
        "Vercel",
      ],
      lane: "right",
    },
    {
      company: "PairTree",
      via: "via nearshore agency",
      role: "Senior Software Engineer",
      workMode: "remote",
      startDate: "Dec 2023",
      endDate: "May 2024",
      description:
        "PairTree is an adoption enablement platform. By connecting adoption professionals, PairTree expands options for expectant moms and creates more opportunities for families pursuing private adoption.",
      bullets: [
        "Translated Figma designed components into responsive web components;",
        "Connected responsive web components to a CMS tool (Sanity), to give autonomy to content managers;",
        "Reduced dependency on developers for website updates by enabling the marketing team to dynamically create new website pages through stacking of web components.",
      ],
      technologies: [
        "GitHub Copilot",
        "JavaScript",
        "TypeScript",
        "Node.js",
        "Next.js",
        "React.js",
        "Tailwind.css",
        "Figma",
        "Vercel",
        "Sanity.io",
      ],
      lane: "right",
    },
    {
      company: "PureCars",
      via: "via nearshore agency",
      role: "Senior Software Engineer",
      workMode: "remote",
      startDate: "May 2022",
      endDate: "Aug 2023",
      description:
        "PureCars is a provider of automotive marketing services for car dealers, helping dealerships implement a comprehensive strategy to get more leads, sales, and service appointments through a wide range of social media channels.",
      bullets: [
        "Designed and implemented visual prototypes for a highly interactive web tool;",
        "Architected and developed robust, efficient, and fail-proof custom metric reports for Data Warehouse Team;",
        "Fixed bugs and enhanced platform features to help users fully leverage the tool's potential.",
      ],
      technologies: [
        "JavaScript",
        "TypeScript",
        "Node.js",
        "React.js",
        "Figma",
        "Docker",
      ],
      lane: "right",
    },
    {
      company: "Radical Imaging",
      via: "via nearshore agency",
      role: "Senior Software Engineer",
      workMode: "remote",
      startDate: "Nov 2021",
      endDate: "Apr 2022",
      description:
        "Radical Imaging is a boutique software consulting agency specializing in custom web and cloud-based solutions for the medical imaging industry, to help healthcare clients solve complex imaging challenges and improve patient care.",
      bullets: [
        "Developed and enhanced open-source applications for medical image visualization (microscopy, tomography, MRI);",
        "Created custom packed imaging software solutions for hospitals, aiming for clinical use.",
      ],
      technologies: [
        "JavaScript",
        "Node.js",
        "React.js",
        "Figma",
        "Docker",
        "AWS",
        "open source software",
      ],
      lane: "right",
    },
    {
      company: "Écolheita",
      role: "Full-Stack Software Development (Freelancing)",
      workMode: "remote",
      startDate: "Jun 2021",
      endDate: "Jun 2024",
      description:
        "Écolheita is a startup created with a mission to combat food waste, by offering products near their expiration date at significant discounts. Customers had the option to either pick up these items in-store or have them delivered to their homes for added convenience.",
      bullets: [
        "Built a platform to combat food waste by offering discounted near-expiration products.",
        "Designed, developed, and launched a native mobile app, web app, and backend server.",
        "Delivered end-to-end solutions aligning business objectives with user experience.",
      ],
      technologies: [
        "JavaScript",
        "Node.js",
        "React.js",
        "React Native",
        "Figma",
        "MongoDB",
        "Docker",
        "AWS",
        "Google Cloud Platform",
      ],
      lane: "left",
      stickyThrough: "PairTree",
    },
    {
      company: "Quero Educação",
      role: "Senior Full-Stack Software Developer",
      workMode: "remote",
      startDate: "Sep 2020",
      endDate: "Feb 2021",
      description:
        "Quero Educação is a Brazilian educational technology (edtech) company founded in 2012, with the mission of democratizing access to education in Brazil. It operates as a large marketplace, primarily through its product Quero Bolsa, which connects students with educational institutions (higher education, basic, technical, and language courses) by offering scholarships and detailed information.",
      bullets: [
        "Led the migration of a legacy PHP monolithic system to a distributed Node.js microservices architecture;",
        "Designed and implemented management and administration software for schools and scholarship programs;",
        "Oversaw technical strategy and ensure seamless transition while maintaining system reliability;",
        "Coordinated with stakeholders to align development with organizational objectives.",
      ],
      technologies: [
        "PHP",
        "JavaScript",
        "Node.js",
        "Vue.js",
        "GitHub Actions",
        "Docker",
        "Kubernetes",
        "AWS",
      ],
      lane: "left",
    },
    {
      company: "Spark Networks",
      role: "Senior Full-Stack Software Developer",
      workMode: "in office",
      startDate: "Dec 2017",
      endDate: "Dec 2019",
      location: "Berlin, Germany",
      description:
        "Spark Networks is a dating company that formerly operated a portfolio of online dating apps and websites targeting various demographics. The company focused on serious relationships for singles over 40 and faith-based communities.",
      bullets: [
        "Developed a library of intelligent, reusable components for scalable niche dating apps (e.g., Jewish and elderly communities).",
        "Designed dynamic email campaigns for multiple brands across different countries.",
        "Built content moderation and fraud prevention tools to support customer care agents.",
        "Ensured platform scalability and maintainability through modular architecture.",
      ],
      technologies: [
        "JavaScript",
        "TypeScript",
        "Node.js",
        "React.js",
        "Redux",
        "MongoDB",
        "RabbitMQ",
        "Webpack",
        "Gitlab CI",
        "Docker",
        "Kubernetes",
      ],
      lane: "right",
    },
    {
      company: "Daitan Group",
      role: "Senior Full-Stack Software Developer",
      workMode: "in office",
      startDate: "Jul 2016",
      endDate: "Oct 2017",
      description:
        "Daitan Group was a software development and engineering company founded in 2004, known for providing services in areas like AI, data engineering, cloud, and microservices for technology vendors.",
      bullets: [
        "Migrated a monolithic Ruby on Rails application to a microservices-oriented architecture using Node.js.",
        "Developed a scalable, reliable portal for VMWare products.",
        "Integrated data from multiple commercial representatives through a CMS.",
        "Ensured system maintainability and performance throughout the migration process.",
      ],
      technologies: [
        "JavaScript",
        "Ruby on Rails",
        "TypeScript",
        "Node.js",
        "Angular.js",
        "Angular 2",
        "Google Analytics",
        "Redis",
        "PostgreSQL",
        "Git",
        "Docker",
        "Codeship",
      ],
      lane: "left",
    },
    {
      company: "Dextra",
      role: "Mid-Level Full-Stack Software Developer",
      workMode: "in office",
      startDate: "Feb 2016",
      endDate: "May 2016",
      description:
        "Dextra was a Brazilian software development company specializing in creating end-to-end digital products by combining design, agile development, and data science.",
      bullets: [
        "Maintained and supported legacy military systems developed in Java.",
        "Provided training and knowledge transfer to IT professionals with outdated skill sets.",
        "Ensured system reliability and continuity while mentoring staff on modern practices.",
      ],
      technologies: ["Java", "JavaScript", "Oracle Database", "Docker"],
      lane: "right",
    },
    {
      company: "Coyô",
      role: "Mid-Level Full-Stack Software Developer",
      workMode: "in office",
      startDate: "Jul 2015",
      endDate: "Dec 2015",
      description:
        "Coyô Software e Comunicação is a Brazilian full-stack digital advertising agency and software house focused on strategic digital campaigns, branding, and web application development.",
      bullets: [
        "Developed APIs and backend services for the blood bank medical industry using Ruby on Rails.",
        "Designed and implemented rich, user-friendly interfaces with JavaScript.",
        "Established continuous integration workflows to streamline software delivery.",
        "Ensured system reliability, scalability, and maintainability for healthcare applications.",
      ],
      technologies: [
        "JavaScript",
        "Ruby on Rails",
        "PostgreSQL",
        "Redis",
        "Angular.js",
      ],
      lane: "left",
    },
    {
      company: "CI&T",
      role: "Mid-Level Full-Stack Software Developer",
      workMode: "in office",
      startDate: "Feb 2015",
      endDate: "Jul 2015",
      description:
        "CI&T is a Brazilian-founded, publicly traded company that provides global digital transformation and software engineering services to large enterprises and fast-growing companies.",
      bullets: [
        'Performed full-stack development on the "M4 Context Engine" module for Motorola\'s Motomaker customization software.',
        "Collaborated with over four cross-functional teams across the globe.",
        "Contributed to the development of the new global version of the Motomaker platform.",
        "Ensured seamless integration and functionality across modules in a complex system.",
      ],
      technologies: [
        "Java",
        "Scala",
        "JavaScript",
        "Ruby on Rails",
        "Angular.js",
        "Cassandra",
        "Redis",
        "Git",
      ],
      lane: "right",
    },
    {
      company: "ACTi",
      role: "Junior Java Web Developer",
      workMode: "in office",
      startDate: "Jun 2014",
      endDate: "Nov 2014",
      description:
        "ACTi is a Brazilian company of project, development, integration of information systems applied to business management and automation of industrial/commercial information, which operates since 2003.",
      bullets: [
        "Analyzed and developed financial, sales, inventory, and purchasing modules within a business management ERP.",
        "Led the migration of the ERP from Windows Forms to web and mobile platforms.",
        "Ensured system functionality, performance, and reliability across new platforms.",
        "Delivered end-to-end solutions while maintaining data integrity and usability.",
      ],
      technologies: [
        "Android",
        "Java",
        "JavaScript",
        "PostgreSQL",
        "HTML5",
        "CSS3",
        "Git",
      ],
      lane: "left",
    },
    {
      company: "VPSA",
      role: "Junior Java Web Developer",
      workMode: "in office",
      startDate: "Jun 2013",
      endDate: "Jun 2014",
      description:
        "Point of Sale (POS) module development within a business management ERP.",
      bullets: [
        "Developed and maintained the Point of Sale (POS) module within a business management ERP using Java.",
        "Collaborated with the ERP team to integrate POS functionality with other modules.",
      ],
      technologies: [
        "Java",
        "JavaScript",
        "PostgreSQL",
        "Oracle SQL",
        "HTML",
        "CSS",
        "Git",
        "SVN",
      ],
      lane: "right",
    },
    {
      company: "Dash",
      role: "Software Developer Intern",
      workMode: "in office",
      startDate: "Jan 2012",
      endDate: "Jan 2013",
      description:
        "First job as Intern, working in web applications with C# and JavaScript.",
      bullets: [
        "Developed websites and computer systems for outsourcing projects with Toyota and Honda.",
        "Built and maintained internal software products for the company.",
      ],
      technologies: [
        ".NET Framework",
        "GeneXus",
        "HTML",
        "CSS",
        "JavaScript",
        "SQL Server",
      ],
      lane: "left",
    },
  ],

  education: [
    {
      school: "ETEP — Escola Técnica Professor Everardo Passos",
      degree: "High School and Computer Technician",
      period: "2009 — 2011",
    },
  ],

  skills: [
    {
      name: "AI tools (Claude Code, Cursor, etc)",
      category: "AI",
      area: "AI",
      level: "Experienced",
      stars: 3,
      years: 2,
      filledDots: 2,
      totalDots: 10,
      since: "2024 until now",
      aliases: ["Claude Code", "Cursor", "GitHub Copilot"],
    },
    {
      name: "JavaScript",
      category: "Languages",
      area: "Back-end · Front-end",
      level: "Expert",
      stars: 5,
      years: 10,
      filledDots: 10,
      totalDots: 10,
      since: "2011 until now",
      aliases: ["JavaScript"],
    },
    {
      name: "TypeScript",
      category: "Languages",
      area: "Back-end · Front-end",
      level: "Advanced",
      stars: 4,
      years: 8,
      filledDots: 8,
      totalDots: 10,
      since: "2017 until now",
      aliases: ["TypeScript"],
    },
    {
      name: "Python",
      category: "Languages",
      area: "Back-end · Infrastructure",
      level: "Experienced",
      stars: 3,
      years: 2,
      filledDots: 2,
      totalDots: 10,
      since: "2024 until now",
      aliases: ["Python"],
    },
    {
      name: "Ruby (on Rails)",
      category: "Languages",
      area: "Back-end · Front-end",
      level: "Experienced",
      stars: 3,
      years: 2,
      filledDots: 2,
      totalDots: 10,
      since: "2015 — 2017",
      aliases: ["Ruby on Rails"],
    },
    {
      name: "React.js",
      category: "Frameworks",
      area: "Front-end",
      level: "Expert",
      stars: 5,
      years: 8,
      filledDots: 8,
      totalDots: 10,
      since: "2018 until now",
      aliases: ["React.js"],
    },
    {
      name: "React Native",
      category: "Frameworks",
      area: "Front-end · Mobile",
      level: "Experienced",
      stars: 3,
      years: 4,
      filledDots: 4,
      totalDots: 10,
      since: "2021 — 2025",
      aliases: ["React Native"],
    },
    {
      name: "Next.js, Vite, TanStack",
      category: "Frameworks",
      area: "Front-end",
      level: "Experienced",
      stars: 3,
      years: 2,
      filledDots: 2,
      totalDots: 10,
      since: "2024 until now",
      aliases: ["Next.js", "Vite", "TanStack"],
    },
    {
      name: "Figma",
      category: "Design",
      area: "Front-end",
      level: "Experienced",
      stars: 3,
      years: 4,
      filledDots: 4,
      totalDots: 10,
      since: "2021 until now",
      aliases: ["Figma"],
    },
    {
      name: "Node.js",
      category: "Runtimes",
      area: "Back-end",
      level: "Expert",
      stars: 5,
      years: 8,
      filledDots: 8,
      totalDots: 10,
      since: "2017 until now",
      aliases: ["Node.js"],
    },
    {
      name: "MongoDB / Redis (NoSQL)",
      category: "Databases",
      area: "Back-end · Data",
      level: "Advanced",
      stars: 4,
      years: 8,
      filledDots: 8,
      totalDots: 10,
      since: "2016 — 2024",
      aliases: ["MongoDB", "Redis"],
    },
    {
      name: "PostgreSQL / MySQL (SQL)",
      category: "Databases",
      area: "Back-end · Data",
      level: "Advanced",
      stars: 4,
      years: 5,
      filledDots: 5,
      totalDots: 10,
      since: "2011 — 2015, 2024 — 2025",
      aliases: ["PostgreSQL", "MySQL"],
    },
    {
      name: "CMS (Sanity, Payload, etc)",
      category: "CMS",
      area: "Back-end · Front-end · Data",
      level: "Experienced",
      stars: 3,
      years: 2,
      filledDots: 2,
      totalDots: 10,
      since: "2024 — 2026",
      aliases: ["Sanity", "Sanity.io", "Payload"],
    },
    {
      name: "AWS",
      category: "Infrastructure",
      area: "Back-end · Data · Observability",
      level: "Experienced",
      stars: 3,
      years: 3,
      filledDots: 3,
      totalDots: 10,
      since: "2022 — 2025",
      aliases: ["AWS"],
    },
    {
      name: "Docker",
      category: "Infrastructure",
      area: "Infrastructure",
      level: "Advanced",
      stars: 4,
      years: 9,
      filledDots: 9,
      totalDots: 10,
      since: "2018 until now",
      aliases: ["Docker"],
    },
    {
      name: "Git and CI/CD",
      category: "Infrastructure",
      area: "Version control",
      level: "Advanced",
      stars: 4,
      years: 9,
      filledDots: 9,
      totalDots: 10,
      since: "2017 until now",
      aliases: [
        "Git",
        "GitHub Actions",
        "Gitlab CI",
        "Buildkite",
        "Codeship",
        "SVN",
      ],
    },
    {
      name: "English",
      category: "Communication",
      area: "Spoken · Written",
      level: "Advanced",
      stars: 4,
      years: 9,
      filledDots: 9,
      totalDots: 10,
      since: "2017 until now",
      aliases: ["English"],
      emoji: "🇺🇸",
    },
    {
      name: "Portuguese",
      category: "Communication",
      area: "Native · Spoken · Written",
      level: "Expert",
      stars: 5,
      years: 0,
      filledDots: 0,
      totalDots: 10,
      since: "Native speaker",
      aliases: ["Portuguese"],
      emoji: "🇧🇷",
      omitExperienceBar: true,
    },
  ],

  milestones: [
    {
      year: 2026,
      text: "❓ 2026 — Looking for new opportunities.",
    },
    {
      year: 2021,
      text: "👔 2021 — Career shift: now working remotely as a contractor. Prioritizing clients from the US and EU.",
    },
    {
      year: 2017,
      text: "⭐ 2017 — Career achievement: working abroad. VISA sponsored to live and work in Berlin, Germany, by a leading global dating company with more than 1 million active monthly subscriptions.",
    },
    {
      year: 2016,
      text: "🎉 2016 — Ascended to senior level developer, defining Node.js as a career mastery goal. Kept working in multidisciplinary environments with Ruby on Rails and JavaScript.",
    },
    {
      year: 2014,
      text: "🎉 2014 — Ascended to mid level developer, working in multidisciplinary environments with Java, Ruby on Rails and JavaScript.",
    },
    {
      year: 2013,
      text: "🎉 2013 — Ascended to junior developer, now working as a full stack web developer with Java.",
    },
    {
      year: 2012,
      text: "⛳ 2012 — Acquired first job as Intern, working in web applications with C# and JavaScript.",
    },
  ],
};
