/** @deprecated Import from `@/cv/cv-colors` for new code. Re-exported for Work section imports. */
export {
  CV_COLORS,
  cvBgAccent,
  cvBgForeground,
  cvBorderAccent,
  cvTextAccent,
  cvTextForeground,
  cvTextMuted,
  cvTextMutedAlt,
  workBadge,
  workBadgeOnDark,
  workBody,
  workCardCollapsed,
  workCardExpanded,
  workCardTriggerHover,
  workDatePillDefault,
  workMeta,
  workMetaOnDark,
  workSpineFill,
  workSpineTrack,
  workSubtitle,
  workTitle,
} from "@/cv/cv-colors";
